"""
WeaveFault ReasoningChain — store and expose per-row LLM reasoning audit trails.

Every FMEA row generated by WeaveFault includes a complete reasoning chain
that explains why each score was assigned. This module manages storage and
retrieval of those chains.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class ReasoningStep:
    """A single step in an LLM reasoning chain."""

    step_number: int
    description: str
    conclusion: str
    score_assigned: int | float | None = None
    score_type: str = ""  # "severity" | "occurrence" | "detection"


@dataclass
class ReasoningChain:
    """
    Full reasoning audit trail for one FMEA row.

    Stores the complete LLM reasoning used to assign RPN scores,
    enabling auditability and human review.
    """

    row_id: str
    component_id: str
    failure_mode: str
    steps: list[ReasoningStep] = field(default_factory=list)
    raw_reasoning: str = ""
    model_used: str = ""
    generated_at: datetime = field(default_factory=datetime.utcnow)

    def add_step(
        self,
        description: str,
        conclusion: str,
        score: int | float | None = None,
        score_type: str = "",
    ) -> None:
        """Add a reasoning step to the chain."""
        self.steps.append(
            ReasoningStep(
                step_number=len(self.steps) + 1,
                description=description,
                conclusion=conclusion,
                score_assigned=score,
                score_type=score_type,
            )
        )

    def to_markdown(self) -> str:
        """Format the reasoning chain as readable Markdown."""
        lines = [
            f"### Reasoning Chain — {self.failure_mode}",
            f"**Component:** {self.component_id}  ",
            f"**Model:** {self.model_used}  ",
            f"**Generated:** {self.generated_at.isoformat()}",
            "",
        ]
        if self.steps:
            for step in self.steps:
                lines.append(f"**Step {step.step_number}: {step.description}**")
                lines.append(f"→ {step.conclusion}")
                if step.score_assigned is not None:
                    lines.append(f"*Score ({step.score_type}): {step.score_assigned}*")
                lines.append("")
        else:
            lines.append(self.raw_reasoning)
        return "\n".join(lines)

    def summary(self) -> str:
        """Return a one-line summary of the reasoning."""
        if self.steps:
            return " | ".join(s.conclusion for s in self.steps)
        return self.raw_reasoning[:200]
