"""
WeaveFault FMEAFormatter — structure FMEA rows to AIAG / IEC 60812 format.

Converts internal FMEARow objects into ordered, standard-compliant
dictionaries ready for export.
"""

from __future__ import annotations

import json

from weavefault.ingestion.schema import FMEADocument, FMEARow
from weavefault.standards import (
    canonical_standard_name,
    get_score_header_labels,
    load_standard_profile,
)

# Column order for AIAG FMEA-4
AIAG_COLUMNS = [
    "component_id",
    "component_name",
    "failure_mode",
    "potential_effect",
    "cascade_effects",
    "severity",
    "occurrence",
    "detection",
    "rpn",
    "recommended_action",
    "standard_clause",
    "standard_metadata",
    "reasoning_chain",
    "confidence",
    "generated_by",
]

# Column order for IEC 60812
IEC_60812_COLUMNS = [
    "component_id",
    "component_name",
    "failure_mode",
    "potential_effect",
    "cascade_effects",
    "severity",
    "occurrence",
    "detection",
    "rpn",
    "standard_clause",
    "standard_metadata",
    "recommended_action",
    "reasoning_chain",
    "confidence",
    "generated_by",
]

STANDARD_COLUMNS = {
    "AIAG_FMEA4": AIAG_COLUMNS,
    "AIAG": AIAG_COLUMNS,
    "IEC_60812": IEC_60812_COLUMNS,
    "MIL_STD_1629": IEC_60812_COLUMNS,
    "ISO_26262": AIAG_COLUMNS,
}


class FMEAFormatter:
    """
    Format FMEA rows to a specific standard's column order and conventions.
    """

    def __init__(self, standard: str = "IEC_60812") -> None:
        self.standard = canonical_standard_name(standard)
        self.standard_profile = load_standard_profile(self.standard)
        self.columns = STANDARD_COLUMNS.get(self.standard, IEC_60812_COLUMNS)

    def format_row(self, row: FMEARow) -> dict:
        """
        Convert a FMEARow to an ordered dict matching the standard's column layout.

        Args:
            row: FMEA row to format.

        Returns:
            Ordered dict with columns in standard order.
        """
        raw = row.model_dump()
        raw["cascade_effects"] = " | ".join(row.cascade_effects)
        raw["standard_metadata"] = (
            json.dumps(row.standard_metadata, sort_keys=True)
            if row.standard_metadata
            else ""
        )

        return {col: raw.get(col, "") for col in self.columns}

    def format_document(self, doc: FMEADocument) -> list[dict]:
        """
        Format all rows in an FMEADocument.

        Args:
            doc: Full FMEA document.

        Returns:
            List of formatted row dicts.
        """
        return [self.format_row(row) for row in doc.rows]

    def get_header_labels(self) -> dict[str, str]:
        """Return human-readable column labels for the active standard."""
        score_headers = get_score_header_labels(self.standard_profile)
        labels = {
            "component_id": "Component ID",
            "component_name": "Component / Function",
            "failure_mode": "Failure Mode",
            "potential_effect": "Potential Effect of Failure",
            "cascade_effects": "Cascade Effects",
            "severity": score_headers["severity"],
            "occurrence": score_headers["occurrence"],
            "detection": score_headers["detection"],
            "rpn": "RPN",
            "recommended_action": "Recommended Action",
            "standard_clause": "Standard Clause",
            "standard_metadata": "Standard Metadata",
            "reasoning_chain": "AI Reasoning",
            "confidence": "Confidence",
            "generated_by": "Generated By",
        }
        return {
            col: labels.get(col, col.replace("_", " ").title()) for col in self.columns
        }
